services:
  gitlab:
    image: gitlab/gitlab-ce:18.0.3-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://git.home'
    # ports:
    #   - '80:80'
      # - '443:443'
      # - '22:22'
    volumes:
      - './GITLAB_HOME/config:/etc/gitlab'
      - './GITLAB_HOME/logs:/var/log/gitlab'
      - './GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`git.home`)"

    networks:
      - web

networks:
  web:
    external: true